# Traffic Density notebook
__example Munich__

In [1]:
import pandas as pd
import psycopg2
import json
from sql import engine #adjust this as necessary to match your sql.py connection methods
from sql import query #get_data = query


f_hamburg = open('/Users/evo/Desktop/Capstone-Project/tomtom/tom_tom_results_Hamburg.json')
f_muenchen = open('/Users/evo/Desktop/Capstone-Project/tomtom/tom_tom_results_Muenchen.json')
f_koeln = open('/Users/evo/Desktop/Capstone-Project/tomtom/tom_tom_results_Koeln.json')
f_frankfurt_am_main = open('/Users/evo/Desktop/Capstone-Project/tomtom/tom_tom_results_Frankfurt_am_Main.json')
f_berlin = open('/Users/evo/Desktop/Capstone-Project/tomtom/tom_tom_results_Berlin.json')
data_hamburg = json.load(f_hamburg)
data_muenchen = json.load(f_muenchen)
data_koeln = json.load(f_koeln)
data_frankfurt_am_main = json.load(f_frankfurt_am_main)
data_berlin = json.load(f_berlin)

density_hamburg = pd.json_normalize(data_hamburg, sep="_")
density_koeln = pd.json_normalize(data_muenchen, sep="_")
density_muenchen = pd.json_normalize(data_koeln, sep="_")
density_frankfurt_am_main = pd.json_normalize(data_frankfurt_am_main, sep="_")
density_berlin = pd.json_normalize(data_berlin, sep="_")

In [2]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
country = []
city = []
for a in density_hamburg["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    country.append('Deutschland')
    city.append('hamburg')
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [3]:
network_hamburg = pd.DataFrame({
    'country': country,
    'city': city,
    'id': id,
    'newid': Newid,
    "speed_limit":speedLimit,
    "road_type":frc,
    "street_name":streetName,
    "street_distance":distance,
    "street_shape":shape,
    "cars":sampleSize,
    "harmonic_average_speed":harmonicAverageSpeed
})

In [4]:
network_hamburg = network_hamburg.query('cars > 0')

In [5]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
country = []
city = []
for a in density_muenchen["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    country.append('Deutschland')
    city.append('muenchen')
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [6]:
network_muenchen = pd.DataFrame({
    'country': country,
    'city': city,
    'id': id,
    'newid': Newid,
    "speed_limit":speedLimit,
    "road_type":frc,
    "street_name":streetName,
    "street_distance":distance,
    "street_shape":shape,
    "cars":sampleSize,
    "harmonic_average_speed":harmonicAverageSpeed
    })

In [7]:
network_muenchen = network_muenchen.query('cars > 0')

In [8]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
country = []
city = []
for a in density_koeln["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    country.append('Deutschland')
    city.append('koeln')
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [9]:
network_koeln = pd.DataFrame({
    'country': country,
    'city': city,
    'id': id,
    'newid': Newid,
    "speed_limit":speedLimit,
    "road_type":frc,
    "street_name":streetName,
    "street_distance":distance,
    "street_shape":shape,
    "cars":sampleSize,
    "harmonic_average_speed":harmonicAverageSpeed
    })

In [10]:
network_koeln = network_koeln.query('cars > 0')

In [11]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
country = []
city = []
for a in density_frankfurt_am_main["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    country.append('Deutschland')
    city.append('frankfurt am main')
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [12]:
network_frankfurt_am_main = pd.DataFrame({
    'country': country,
    'city': city,
    'id': id,
    'newid': Newid,
    "speed_limit":speedLimit,
    "road_type":frc,
    "street_name":streetName,
    "street_distance":distance,
    "street_shape":shape,
    "cars":sampleSize,
    "harmonic_average_speed":harmonicAverageSpeed
    })

In [13]:
network_frankfurt_am_main = network_frankfurt_am_main.query('cars > 0')

In [14]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
country = []
city = []
for a in density_berlin["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    country.append('Deutschland')
    city.append('berlin')
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [15]:
network_berlin = pd.DataFrame({
    'country': country,
    'city': city,
    'id': id,
    'newid': Newid,
    "speed_limit":speedLimit,
    "road_type":frc,
    "street_name":streetName,
    "street_distance":distance,
    "street_shape":shape,
    "cars":sampleSize,
    "harmonic_average_speed":harmonicAverageSpeed
    })

In [16]:
network_berlin = network_berlin.query('cars > 0')

In [23]:
network_berlin

,country,city,id,newid,speed_limit,road_type,street_name,street_distance,street_shape,cars,harmonic_average_speed
0,Deutschland,berlin,-12760000151662,-00004435-3800-0400-0000-000000d5a611,20,7,Benekendorffstraße,131.28,"[{'latitude': 52.61413, 'longitude': 13.33502}...",191,27.76
1,Deutschland,berlin,-12760000006484,-00004435-3800-0400-0000-000000d5a615,20,7,Ziegeleiweg,132.50,"[{'latitude': 52.6148, 'longitude': 13.33676},...",1,30.30
2,Deutschland,berlin,-12760000086575,-00004435-3800-0400-0000-000000d5a619,35,6,Zehntwerderweg,154.23,"[{'latitude': 52.6171, 'longitude': 13.33976},...",72,18.87
3,Deutschland,berlin,-12760000333480,-00004435-3800-0400-0000-000000d5a621,50,5,Zabel-Krüger-Damm,10.22,"[{'latitude': 52.61353, 'longitude': 13.34388}...",9216,33.89
4,Deutschland,berlin,-12760000547047,-00004435-3800-0400-0000-000000d5a622,50,5,Zabel-Krüger-Damm,59.51,"[{'latitude': 52.61384, 'longitude': 13.34459}...",10816,20.55
...,...,...,...,...,...,...,...,...,...,...,...
215599,Deutschland,berlin,12760017956120,fff397a7-a483-43d9-b8aa-98430ed141c8,35,6,Weidenweg,170.19,"[{'latitude': 52.52686, 'longitude': 13.13821}...",1335,17.27
215604,Deutschland,berlin,12760012107017,fffb1b47-825c-4229-a20e-c658a8ae378e,50,4,Am Kiesteich,69.74,"[{'latitude': 52.54331, 'longitude': 13.15804}...",12179,39.32
215605,Deutschland,berlin,12760011037997,fffbb4a6-e664-4e91-afc1-3815e37e5121,35,6,Bärensteinstraße,12.89,"[{'latitude': 52.54088, 'longitude': 13.56828}...",682,14.66
215606,Deutschland,berlin,12760018001998,fffdebef-c86f-44d0-9ee5-23ec8659f761,20,7,None,39.05,"[{'latitude': 52.55296, 'longitude': 13.43914}...",56,5.68
215607,Deutschland,berlin,12760017507747,fffffd44-753c-4c42-b59c-ed153bf13fab,35,6,Lindenstraße,164.79,"[{'latitude': 52.48421, 'longitude': 13.57595}...",214,20.32

In [17]:
hamburg_harmonic_avg_speed = round(network_hamburg['harmonic_average_speed'].mean(), 2)
hamburg_harmonic_avg_speed_max = network_hamburg['harmonic_average_speed'].max()
hamburg_avg_density = network_hamburg['cars'].mean()
muenchen_harmonic_avg_speed = round(network_muenchen['harmonic_average_speed'].mean(), 2)
muenchen_harmonic_avg_speed_max = network_muenchen['harmonic_average_speed'].max()
muenchen_avg_density = network_muenchen['cars'].mean()
koeln_harmonic_avg_speed = round(network_koeln['harmonic_average_speed'].mean(), 2) 
koeln_harmonic_avg_speed_max = network_koeln['harmonic_average_speed'].max()
koeln_avg_density = network_koeln['cars'].mean()
frankfurt_am_main_harmonic_avg_speed = round(network_frankfurt_am_main['harmonic_average_speed'].mean(), 2)
frankfurt_am_main_harmonic_avg_speed_max = network_frankfurt_am_main['harmonic_average_speed'].max()
frankfurt_am_main_avg_density = network_frankfurt_am_main['cars'].mean()
berlin_harmonic_avg_speed = round(network_berlin['harmonic_average_speed'].mean(), 2)
berlin_harmonic_avg_speed_max = network_berlin['harmonic_average_speed'].max()
berlin_avg_density = network_berlin['cars'].mean()

In [18]:
network = pd.DataFrame(columns=['country', 'city', 'lat','lon', 'harmonic_avg_speed', 'harmonic_avg_max_speed', 'traffic_density'])

In [19]:
network['country'] = ['Deutschland', 'Deutschland', 'Deutschland', 'Deutschland', 'Deutschland',]
network['city'] = ['hamburg', 'muenchen', 'koeln', 'frankfurt am main', 'berlin']
network['lat'] = [53.550556, 48.137154, 50.936389, 50.116667, 52.518611]
network['lon']= [9.993333, 11.576124, 6.952778, 8.683333, 13.408333]
network['harmonic_avg_speed'] = [hamburg_harmonic_avg_speed, muenchen_harmonic_avg_speed, koeln_harmonic_avg_speed, frankfurt_am_main_harmonic_avg_speed, berlin_harmonic_avg_speed]
network['harmonic_avg_max_speed'] = [hamburg_harmonic_avg_speed_max, muenchen_harmonic_avg_speed_max, koeln_harmonic_avg_speed_max, frankfurt_am_main_harmonic_avg_speed_max, berlin_harmonic_avg_speed_max]
network['traffic_density'] = [hamburg_avg_density, muenchen_avg_density, koeln_avg_density, frankfurt_am_main_avg_density, berlin_avg_density]

In [20]:
network

,country,city,lat,lon,harmonic_avg_speed,harmonic_avg_max_speed,traffic_density
0,Deutschland,hamburg,53.550556,9.993333,23.73,125.80,9302.148414
1,Deutschland,muenchen,48.137154,11.576124,24.63,130.30,9146.005376
2,Deutschland,koeln,50.936389,6.952778,22.85,141.00,9767.684029
3,Deutschland,frankfurt am main,50.116667,8.683333,25.38,138.84,10858.207343
4,Deutschland,berlin,52.518611,13.408333,21.83,129.70,9045.031801

In [21]:
# # Export to csv
network.to_csv('/Users/evo/Documents/neue_fische/capstone_final/csv/traffic_data_city.csv', index=False)

In [22]:
# Specify which table within your database you want to push your data to. Give your table an unambiguous name.
table_name = 'df_network'
schema = 'muc_analytics_21_1'
# If the specified table doesn't exist yet, it will be created
# With 'replace', your data will be replaced if the table already exists.
# This will take a minute or two...

# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        network.to_sql(name=table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema=schema, # Use schmea that was defined earlier
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

The df_network table was imported successfully.