# Traffic Density notebook
__example Munich__

In [1]:
import pandas as pd

import json


f = open('berlin2.json')

data = json.load(f)

In [2]:
print(type(data))

<class 'dict'>

In [3]:
density = pd.json_normalize(data, sep="_")

density

,jobName,creationTime,dateRanges,timeSets,userPreference_distanceUnit,userPreference_includedSpeedLimits,network_networkName,network_zoneId,network_probeSource,network_mapsVersions,network_segmentResults
0,Berlin,2022-02-11T11:06:39.2217Z,"[{'@id': 1, 'name': 'January 2021', 'from': '2...","[{'@id': 2, 'name': '0:00-24:00', 'dayToTimeRa...",KILOMETERS,ALL,Berlin,Europe/Berlin,PASSENGER,[NorthernEurope_TeleAtlasMNR_eur2021.03.000-22...,"[{'segmentId': -12760000151662, 'newSegmentId'..."

In [4]:
density["network_segmentResults"][0][0]

{'segmentId': -12760000151662,
 'newSegmentId': '-00004435-3800-0400-0000-000000d5a611',
 'speedLimit': 20,
 'frc': 7,
 'streetName': 'Benekendorffstra√üe',
 'distance': 131.28,
 'shape': [{'latitude': 52.61413, 'longitude': 13.33502},
  {'latitude': 52.61351, 'longitude': 13.33337}],
 'segmentTimeResults': [{'timeSet': 2,
   'dateRange': 1,
   'harmonicAverageSpeed': 27.76,
   'medianSpeed': 31.5,
   'averageSpeed': 30.96,
   'standardDeviationSpeed': 7.44,
   'travelTimeStandardDeviation': 10.19,
   'sampleSize': 191,
   'averageTravelTime': 17.03,
   'medianTravelTime': 15.0,
   'travelTimeRatio': 1.0,
   'speedPercentiles': [16,
    22,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    34,
    35,
    35,
    36,
    38,
    40,
    42]}]}

In [5]:
id = []
Newid = []
speedLimit = []
frc = []
streetName = []
distance = []
shape = []
segmentTimeResults = []
sampleSize = []
harmonicAverageSpeed = []
for a in density["network_segmentResults"][0]:
    id.append(a.get('segmentId', None))
    Newid.append(a.get('newSegmentId', None))
    speedLimit.append(a.get('speedLimit', None))
    frc.append(a.get('frc',None))
    streetName.append(a.get('streetName',None))
    distance.append(a.get('distance',None))
    shape.append(a.get('shape',None))
    segmentTimeResults.append(a.get('segmentTimeResults',None))
    
for a in segmentTimeResults:
        for i in a:
            sampleSize.append(i.get('sampleSize', None))
            harmonicAverageSpeed.append(i.get('harmonicAverageSpeed',None))

In [7]:
network = pd.DataFrame({
    'id': id,
    'newid': Newid,
    "speedLimit":speedLimit,
    "frc":frc,
    "streetName":streetName,
    "distance":distance,
    "shape":shape,
    "sampleSize":sampleSize,
    "harmonicAverageSpeed":harmonicAverageSpeed
})

In [8]:
network.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215608 entries, 0 to 215607
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    215608 non-null  int64
 1   newid                 215608 non-null  object
 2   speedLimit            215608 non-null  int64
 3   frc                   215608 non-null  int64
 4   streetName            172376 non-null  object
 5   distance              215608 non-null  float64
 6   shape                 215608 non-null  object
 7   sampleSize            215608 non-null  int64
 8   harmonicAverageSpeed  215608 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 14.8+ MB

In [18]:
network.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 214773 entries, 0 to 215607
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    214773 non-null  int64
 1   newid                 214773 non-null  object
 2   speedLimit            214773 non-null  int64
 3   frc                   214773 non-null  int64
 4   streetName            171580 non-null  object
 5   distance              214773 non-null  float64
 6   shape                 214773 non-null  object
 7   sampleSize            214773 non-null  int64
 8   harmonicAverageSpeed  214773 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 16.4+ MB

In [10]:
# ProbeCounts = []
# for a in network["segmentProbeCounts"]:
#     for i in a:
#         ProbeCounts.append(i.get('probeCount', None))

In [11]:
# network["ProbeCounts"] = ProbeCounts

In [12]:
# network.drop("segmentProbeCounts",axis=1,inplace=True)

In [13]:
# network.reset_index(drop=True)

In [14]:
network[network["streetName"].isnull()]

,id,newid,speedLimit,frc,streetName,distance,shape,sampleSize,harmonicAverageSpeed
421,-12760000647355,-00004435-3800-0400-0000-000000d5a8f8,30,5,None,25.84,"[{'latitude': 52.62034, 'longitude': 13.35614}...",77,6.95
503,-12760000092944,-00004435-3800-0400-0000-000000d5a9d8,50,3,None,13.41,"[{'latitude': 52.5939, 'longitude': 13.28228},...",182,8.43
527,-12760000555580,-00004435-3800-0400-0000-000000d5aa32,35,7,None,557.00,"[{'latitude': 52.58203, 'longitude': 13.24351}...",84,33.41
528,-12760000425327,-00004435-3800-0400-0000-000000d5aa33,35,7,None,165.94,"[{'latitude': 52.58101, 'longitude': 13.24528}...",83,29.31
537,-12760000317912,-00004435-3800-0400-0000-000000d5aa54,50,3,None,7.44,"[{'latitude': 52.61452, 'longitude': 13.24781}...",23554,24.28
...,...,...,...,...,...,...,...,...,...
215596,12760011497943,fff0372f-c0c2-48e1-9f22-1f21aa419b94,20,7,None,15.71,"[{'latitude': 52.45902, 'longitude': 13.50798}...",0,0.00
215597,12760011749019,fff124d2-c904-42b3-a283-05c0c8eb7f15,20,7,None,31.91,"[{'latitude': 52.45924, 'longitude': 13.50439}...",0,0.00
215601,12760013680153,fff68f32-f60b-4e8d-bdce-847c322ff510,35,7,None,94.08,"[{'latitude': 52.64301, 'longitude': 13.48252}...",0,0.00
215603,12760016191057,fffa4094-8476-4cf9-96d2-6e0350441f26,35,7,None,305.73,"[{'latitude': 52.64366, 'longitude': 13.45768}...",0,0.00
215606,12760018001998,fffdebef-c86f-44d0-9ee5-23ec8659f761,20,7,None,39.05,"[{'latitude': 52.55296, 'longitude': 13.43914}...",56,5.68

In [15]:
network.query("frc == 0 and speedLimit >= 100")

,id,newid,speedLimit,frc,streetName,distance,shape,sampleSize,harmonicAverageSpeed
22614,-12760000518069,-00004435-3800-0400-0000-000000d66e2c,130,0,A100,13.96,"[{'latitude': 52.47376, 'longitude': 13.36358}...",327440,75.81
22615,-12760000195508,-00004435-3800-0400-0000-000000d66e32,130,0,Sachsendamm,223.73,"[{'latitude': 52.47421, 'longitude': 13.36041}...",369409,70.60
27618,-12760000259777,-00004435-3800-0400-0000-000000d69e57,130,0,None,57.39,"[{'latitude': 52.49821, 'longitude': 13.2724},...",115180,62.42
27619,-12760000259773,-00004435-3800-0400-0000-000000d69e59,130,0,Messedammbr√ºcke,13.64,"[{'latitude': 52.49811, 'longitude': 13.27228}...",115146,64.00
27622,-12760000259776,-00004435-3800-0400-0000-000000d69e70,130,0,None,23.60,"[{'latitude': 52.49795, 'longitude': 13.27207}...",115102,64.39
...,...,...,...,...,...,...,...,...,...
213618,12760017178618,fa69303d-714c-4dcf-822d-da96996f5434,130,0,A114,300.29,"[{'latitude': 52.62705, 'longitude': 13.42802}...",35468,60.82
214254,12760013343915,fc1c1b8e-77f3-435f-8f9e-7a315de64786,120,0,A100,16.66,"[{'latitude': 52.46897, 'longitude': 13.45974}...",0,0.00
214707,12760013592000,fd7b78c8-f61b-42d3-84f1-fc196103fdfe,120,0,A100,753.88,"[{'latitude': 52.47756, 'longitude': 13.46196}...",0,0.00
215123,12760013343930,fea08e4f-e8b3-4e3b-a4e0-25bdb5bfe0e2,120,0,A100,97.32,"[{'latitude': 52.46588, 'longitude': 13.45798}...",0,0.00
215300,12760013050937,ff239817-4d03-42f1-b1ca-9c4ddb5094ce,120,0,A100,283.16,"[{'latitude': 52.47158, 'longitude': 13.46095}...",0,0.00

In [16]:
network = network.drop(network[(network.frc == 0) & (network.speedLimit >= 100)].index)

In [17]:
network

,id,newid,speedLimit,frc,streetName,distance,shape,sampleSize,harmonicAverageSpeed
0,-12760000151662,-00004435-3800-0400-0000-000000d5a611,20,7,Benekendorffstra√üe,131.28,"[{'latitude': 52.61413, 'longitude': 13.33502}...",191,27.76
1,-12760000006484,-00004435-3800-0400-0000-000000d5a615,20,7,Ziegeleiweg,132.50,"[{'latitude': 52.6148, 'longitude': 13.33676},...",1,30.30
2,-12760000086575,-00004435-3800-0400-0000-000000d5a619,35,6,Zehntwerderweg,154.23,"[{'latitude': 52.6171, 'longitude': 13.33976},...",72,18.87
3,-12760000333480,-00004435-3800-0400-0000-000000d5a621,50,5,Zabel-Kr√ºger-Damm,10.22,"[{'latitude': 52.61353, 'longitude': 13.34388}...",9216,33.89
4,-12760000547047,-00004435-3800-0400-0000-000000d5a622,50,5,Zabel-Kr√ºger-Damm,59.51,"[{'latitude': 52.61384, 'longitude': 13.34459}...",10816,20.55
...,...,...,...,...,...,...,...,...,...
215603,12760016191057,fffa4094-8476-4cf9-96d2-6e0350441f26,35,7,None,305.73,"[{'latitude': 52.64366, 'longitude': 13.45768}...",0,0.00
215604,12760012107017,fffb1b47-825c-4229-a20e-c658a8ae378e,50,4,Am Kiesteich,69.74,"[{'latitude': 52.54331, 'longitude': 13.15804}...",12179,39.32
215605,12760011037997,fffbb4a6-e664-4e91-afc1-3815e37e5121,35,6,B√§rensteinstra√üe,12.89,"[{'latitude': 52.54088, 'longitude': 13.56828}...",682,14.66
215606,12760018001998,fffdebef-c86f-44d0-9ee5-23ec8659f761,20,7,None,39.05,"[{'latitude': 52.55296, 'longitude': 13.43914}...",56,5.68
215607,12760017507747,fffffd44-753c-4c42-b59c-ed153bf13fab,35,6,Lindenstra√üe,164.79,"[{'latitude': 52.48421, 'longitude': 13.57595}...",214,20.32